### ISSUE TITLE
Links should point to the correct region

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#104]
[![Screenshot_2021-05-25_18-11-22.png](https://mrkr.io/s/60ad3dcaa1875a5f50997a88/2)](https://mrkr.io/s/60ad3dcaa1875a5f50997a88/0)

in this case, the seller is from US and the links are pointing to europe

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://amazondemo.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced](https://amazondemo.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced)

<table><tr><td><strong>Browser</strong></td><td>Chrome 90.0.4430.212</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 637</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
This was fixed with the 2.0.2. Closing.
