### ISSUE TITLE
Shipping address on Amazon Pay are not available when they should be

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#108]
**Describe the bug**
The addresses on Amazon Pay are not available for the Amazon pay shoppers when some settings are present on the shipping zones

Settings of the site:
https://amazondemo.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=shipping
https://amazondemo.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=general

**To Reproduce**
1. Checkout with Amazon Pay the address of US should be available but they are not

**Screenshots**
![image](https://user-images.githubusercontent.com/43881685/120204556-5746a180-c1ff-11eb-8477-4c210f3e352e.png)

**Expected behavior**
US address should be available

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by msaggiorato** [comment]
With the current settings:

![image](https://user-images.githubusercontent.com/6192180/120537379-9a4d7400-c3bb-11eb-9d64-2342c6ce4ce9.png)

![image](https://user-images.githubusercontent.com/6192180/120537412-a5080900-c3bb-11eb-9834-7513d980a333.png)

I get the desired results:

![image](https://user-images.githubusercontent.com/6192180/120537526-c668f500-c3bb-11eb-9db0-4b80f594114b.png)

Not sure if this is still reproducible, or maybe i'm not having the right settings.
