### ISSUE TITLE
"Disconnect Amazon Pay" is deleting only the Public Key Id

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#11]
[![Screenshot_2020-11-30_19-16-24.png](https://mrkr.io/s/5fc5450888081f79e82a97ed/2)](https://mrkr.io/s/5fc5450888081f79e82a97ed/0)

https://drive.google.com/file/d/1bsgsVlFxsfPqfZPkbf8Ra1yaquBDzDxT/view?usp=sharing

should also delete Merchant ID and Store ID

---

**Reported by:** Christian Fricker (christian@saucal.com)
**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced](https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced)
<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.66</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 637</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
This was intentionally built like this, since this doesn't change when the merchant is logging in again. But it does make sense to delete them all. Any objections @lauramelos ?
