### ISSUE TITLE
After manual importing keys Amazon Pay notice is still there

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#14]
[![Screenshot_2020-12-01_15-02-41.png](https://mrkr.io/s/5fc65b11d205cb44a5a8e6a7/2)](https://mrkr.io/s/5fc65b11d205cb44a5a8e6a7/0)

After manual importing keys Amazon Pay notice should not be there

---

**Reported by:** Christian Fricker (christian@saucal.com)
**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced](https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced)
<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.66</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 637</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by ChristianAF** [comment]
Also when importing settings

**Comment by msaggiorato** [comment]
Yes, this is because the check for the notice happen before the settings are in place. I've noted this, but didn't get to it yet.
