### ISSUE TITLE
Export Setting is only exporting the Merchant account details

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#15]
[![Screenshot_2020-12-01_15-20-03.png](https://mrkr.io/s/5fc65f239c4d0944a4760407/2)](https://mrkr.io/s/5fc65f239c4d0944a4760407/0)

---

**Reported by:** Christian Fricker (christian@saucal.com)
**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced](https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced)
<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.66</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 576</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
What do you mean, only Merchant Account details?

**Comment by ChristianAF** [comment]
is not getting the Advanced configuration Section

**Comment by msaggiorato** [comment]
![image](https://user-images.githubusercontent.com/6192180/101526722-ca1b4200-396b-11eb-9fb8-165d4d6cecfc.png)

Seems to work fine for me (even tho there's some garbage there), which i'll report separately.
