### ISSUE TITLE
(V1) - Two different methods of refuning can refund more than the total order

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#20]
[![Screenshot_2020-12-03_14-00-21.png](https://mrkr.io/s/5fc8ef758b03473fd158ee36/2)](https://mrkr.io/s/5fc8ef758b03473fd158ee36/0)

---

**Reported by:** Christian Fricker (christian@saucal.com)
**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/post.php?post=49&action=edit](https://stgamazontest.wpengine.com/wp-admin/post.php?post=49&action=edit)
<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.66</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 637</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by ChristianAF** [comment]
[![Screenshot_2020-12-03_14-01-10.png](https://mrkr.io/s/5fc8efa637d7616a1c79c209/2)](https://mrkr.io/s/5fc8efa637d7616a1c79c209/0)

**Comment by msaggiorato** [comment]
Seems like this whole refund functionality on the sidebar and order view is broken at the very least. Will likely be good to review on the v2 implementation.
