### ISSUE TITLE
Export settings button is only exporting the Private Key 

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#34]
[![Screenshot_2021-01-18_13-02-18.png](https://mrkr.io/s/600586da791a703a93f4d6ff/2)](https://mrkr.io/s/600586da791a703a93f4d6ff/0)

Steps to reproduce:

1. Connect Amazon seller account and save.

2. Click on the "Export" button.

Actual result:

Only Exporting the Private Key

Expected result:

Should export all settings.

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced](https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced)

<table><tr><td><strong>Browser</strong></td><td>Chrome 87.0.4280.88</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 576</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
Fixed in alpha3 delivered today.
