### ISSUE TITLE
Checkout page - not getting the correct billing address from test account

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#35]
[![Screenshot_2021-01-18_13-25-30.png](https://mrkr.io/s/60058c4a54855c3154d3ef19/2)](https://mrkr.io/s/60058c4a54855c3154d3ef19/0)

This is the card selected and billing address
![image](https://user-images.githubusercontent.com/43881685/104921104-a76f4680-5977-11eb-8270-c4674f266f86.png)

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
The cards on v2 are not the cards managed in seller central. This is by design on Amazon's side.
