### ISSUE TITLE
With Amazon Pay is not possible to create and account on Checkout page

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#36]
[![Screenshot_2021-01-18_13-56-44.png](https://mrkr.io/s/6005939c791a703a93f4d750/2)](https://mrkr.io/s/6005939c791a703a93f4d750/0)

Steps to reproduce:
- Settings: https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=account
![image](https://user-images.githubusercontent.com/43881685/104924318-046cfb80-597c-11eb-99f2-e3d0f3a8a047.png)

Common checkout flow

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
Fixed in alpha3 delivered today.

**Comment by ChristianAF** [comment]
[![Screenshot_2021-01-21_14-06-13.png](https://mrkr.io/s/60098a55363b2f3acf5e7574/2)](https://mrkr.io/s/60098a55363b2f3acf5e7574/0)

**Comment by msaggiorato** [comment]
Hey @ChristianAF , this has been addressed in alpha5.

Please test again. The flow is slightly different, but should handle all login cases listed [here](https://eps-eu-external-file-share.s3.eu-central-1.amazonaws.com/Login+flows+with+Account+matching/Login_Account_Matching_-_Pay-Button-initiated_Simplified.pdf)
