### ISSUE TITLE
Amazon account is logged out when CC is declined or canceled buy customer status

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#37]
[![Screenshot_2021-01-18_15-57-17.png](https://mrkr.io/s/6005afddec40043b1689df2e/2)](https://mrkr.io/s/6005afddec40043b1689df2e/0)

Steps to reproduce:

Payment Region: Europe
Payment Capture: Authorized and Capture

Credit Card Used: *3064 and *3434

User is logged out after "BuyerCanceled" or "Declined" status

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
This is due to how the API works in v2. The checkout session cannot be created again without logging the user back in. I've just pushed a "workaround" for this, forcing the person to go back to amazon and select a new payment method.

Will be available in alpha3

**Comment by msaggiorato** [comment]
Workaround available in alpha3 delivered today.
