### ISSUE TITLE
Amazon Pay button is not showing on Cart or checkout (US REgion only)

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#41]
[![Screenshot_2021-01-19_15-41-54.png](https://mrkr.io/s/6006fdc2f8c65f3ad5a41260/2)](https://mrkr.io/s/6006fdc2f8c65f3ad5a41260/0)

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=5](https://stgamazontest.wpengine.com/?page_id=5)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by ChristianAF** [comment]
[![Screenshot_2021-01-19_15-42-25.png](https://mrkr.io/s/6006fde1aebc423a8e401d27/2)](https://mrkr.io/s/6006fde1aebc423a8e401d27/0)

**Comment by ChristianAF** [comment]
![image](https://user-images.githubusercontent.com/43881685/105057522-10c48780-5a54-11eb-90e2-05aca7ba6cca.png)

**Comment by msaggiorato** [comment]
Fixed in alpha3 delivered today.
