### ISSUE TITLE
Some addresses are not restricted on Amazon pay account.

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#49]
[![Screenshot_2021-01-25_13-03-40.png](https://mrkr.io/s/600ec1acbdd9eb0a3b9737e8/2)](https://mrkr.io/s/600ec1acbdd9eb0a3b9737e8/0)

**Steps to reproduce:**

- General Settings: Ship to specific countries. Australia, Japan, Spain 

- Shipping zones: Argentina, Japan, Spain (Madrid). "Locations not covered by your other zones" no rates

**Actual result:**

The addreses from Argentina are not been restricted.

**Expected result:**

The addreses from Argentina should be restricted.

**Comment by ChristianAF** [comment]
with same settings but on "Locations not covered by your other zones" some rate is setted, the restriction is working.

![image](https://user-images.githubusercontent.com/43881685/105709939-2ffc6280-5ef5-11eb-8aae-b7df444ee482.png)

**Comment by msaggiorato** [comment]
Hey @ChristianAF , is this fixed?
