### ISSUE TITLE
Shipping prices are not been shown.

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#55]
[![Screenshot_2021-01-27_12-59-46.png](https://mrkr.io/s/601163c2b113cf310dc6fd38/2)](https://mrkr.io/s/601163c2b113cf310dc6fd38/0)

when shipping method is setted for only Spain, is getting the shipping price. But when is setted to only "Madrid" the shipping is not showing.

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 84.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
And does this happen only with Amazon? Or is it a config glitch in Woo?

**Comment by ChristianAF** [comment]
Only with Amazon. Seems to be something related to State field
