### ISSUE TITLE
Error when opening parent order

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#69]
[![Screenshot_2021-03-10_21-44-13.png](https://mrkr.io/s/60493dade6ff926fa8d430dd/2)](https://mrkr.io/s/60493dade6ff926fa8d430dd/0)

**Steps to reproduce:**
Order created using amazon v2 without migration completed.
**Actual result:**
Parent order details are not displayed
On the browser console it records:
ailed to load resource: the server responded with a status of 500 ()
**Expected result:**
Parent order details should be displayed

Log:
2021-03-10T21:25:28+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Gateway_Amazon_Payments_Advanced_Legacy::get_cached_charge_permission_status() in /nas/content/live/stgamazontest/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/admin/class-wc-amazon-payments-advanced-order-admin.php:181
Stack trace:
#0 /nas/content/live/stgamazontest/wp-includes/class-wp-hook.php(292): WC_Amazon_Payments_Advanced_Order_Admin->auth_box_render(Object(Automattic\WooCommerce\Admin\Overrides\Order), 'v2')
#1 /nas/content/live/stgamazontest/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /nas/content/live/stgamazontest/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /nas/content/live/stgamazontest/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/admin/class-wc-amazon-payments-advanced-order-admin.php(153): do_action('wc_amazon_autho...', Object(Automattic\WooCommerce\Admin\Overrides\Order), 'v2')
#4 /nas/content/live/stgamazontest/wp-admin/includes/template.php(1389): WC in /nas/content/live/stgamazontest/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/admin/class-wc-amazon-payments-advanced-order-admin.php on line 181

---

**Reported by:** Diego Barletta (diegob@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/post.php?post=84&action=edit](https://stgamazontest.wpengine.com/wp-admin/post.php?post=84&action=edit)

<table><tr><td><strong>Browser</strong></td><td>Chrome 89.0.4389.82</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 798</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
This should be fixed on alpha10
