### ISSUE TITLE
Subscriptions with free trial returns an error on checkout

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#70]
[![Screenshot_2021-03-11_19-55-07.png](https://mrkr.io/s/604a759b9f6ca26f7ea3845d/2)](https://mrkr.io/s/604a759b9f6ca26f7ea3845d/0)

**Steps to reproduce:**
Preconditions:
* User logged out
* Have a subscription with free trial

From the shop page add the subscription to cart.
Navigate to cart
Select the "Amazon Pay" button
Notice the error

**Actual result:**
User cannot log in and an error page is loaded
The same issue is present when navigating to Checkout page (instead of cart page)
**Expected result:**
Log in page must be shown in order to the user to use amazon credentials

---

**Reported by:** Diego Barletta (diegob@saucal.com)

**Source URL:** [https://payments.amazon.de/checkout/initiate](https://payments.amazon.de/checkout/initiate)

<table><tr><td><strong>Browser</strong></td><td>Chrome 89.0.4389.82</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 969</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

https://user-images.githubusercontent.com/37819277/110847226-6c103a80-828b-11eb-94fe-342869d5a613.mp4

**Comment by msaggiorato** [comment]
This is fixed in alpha9 (and improved in alpha10)
