### ISSUE TITLE
Is not possible to make a refund using the "Refund" button

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#71]
https://user-images.githubusercontent.com/37819277/110851188-7a605580-828f-11eb-9ab5-a3ca77acbf43.mp4
![2021-03-10_19-57-06](https://user-images.githubusercontent.com/37819277/110851192-7b918280-828f-11eb-9528-5f6814a3371a.png)

[![Screenshot_2021-03-11_20-29-52.png](https://mrkr.io/s/604a7dc086d8ca6fde6b862d/2)](https://mrkr.io/s/604a7dc086d8ca6fde6b862d/0)

**Steps to reproduce:**
*Preconditions:
-The order must be placed on V1
Open a subscription parent order
Navigate to "Item" section
Click on the "Refund" button
**Actual result:**
When using the "Refund" button the following error message is displayed on the browser "No charge to refund on this order" and the refund is not made.

**Expected result:**
The refund must be made with no issues

---

**Reported by:** Diego Barletta (diegob@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/post.php?post=75&action=edit](https://stgamazontest.wpengine.com/wp-admin/post.php?post=75&action=edit)

<table><tr><td><strong>Browser</strong></td><td>Chrome 89.0.4389.82</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 969</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
Reported by @bianchif aswell. Checking this out today.

**Comment by msaggiorato** [comment]
Fixed on alpha11
