### ISSUE TITLE
When renewal process is triggered after trial period an error occurs

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#73]
[![Screenshot_2021-03-15_22-40-37.png](https://mrkr.io/s/604fe265f15fa06fae13a845/2)](https://mrkr.io/s/604fe265f15fa06fae13a845/0)

**Steps to reproduce:**
* Preconditions:
Must have a free trial subscription

Having a free trial subscription wait to the first payment
The following error is recorded in the log:
"2021-03-15T19:14:11+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Gateway_Amazon_Payments_Advanced_Legacy::get_cached_charge_permission_status() in /nas/content/live/stgamazontest/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/admin/class-wc-amazon-payments-advanced-order-admin.php:181
Stack trace:
#0 /nas/content/live/stgamazontest/wp-includes/class-wp-hook.php(292): WC_Amazon_Payments_Advanced_Order_Admin->auth_box_render(Object(Automattic\WooCommerce\Admin\Overrides\Order), 'v2')
#1 /nas/content/live/stgamazontest/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /nas/content/live/stgamazontest/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /nas/content/live/stgamazontest/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/admin/class-wc-amazon-payments-advanced-order-admin.php(153): do_action('wc_amazon_autho...', Object(Automattic\WooCommerce\Admin\Overrides\Order), 'v2')
#4 /nas/content/live/stgamazontest/wp-admin/includes/template.php(1389): WC in /nas/content/live/stgamazontest/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/admin/class-wc-amazon-payments-advanced-order-admin.php on line 181"
**Actual result:**
An error occurs and payment is not made
**Expected result:**
Triggered payment must be processed with no errors

---

**Reported by:** Diego Barletta (diegob@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/edit.php?post_type=shop_subscription](https://stgamazontest.wpengine.com/wp-admin/edit.php?post_type=shop_subscription)

<table><tr><td><strong>Browser</strong></td><td>Chrome 89.0.4389.82</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 969</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

https://user-images.githubusercontent.com/37819277/111231376-e90f1d00-85c7-11eb-81f7-5b16a67884db.mp4

**Comment by msaggiorato** [comment]
This was fixed in alpha10
