### ISSUE TITLE
V2 - Multicurrency - WPML - Amazon Pay is not working

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#86]
[![Screenshot_2021-03-31_22-52-50.png](https://mrkr.io/s/6064fd426fe75020373247c6/2)](https://mrkr.io/s/6064fd426fe75020373247c6/0)

Amazon pay is not working with WPML, only showing the amazon pay option but no log in button

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 87.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 451</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by msaggiorato** [comment]
Fixed in upcoming version.
