### ISSUE TITLE
V2 - Multicurency - Currency Switcher for WooCommerce - Not showing the multicurrency menu

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#88]
[![Screenshot_2021-04-01_19-46-46.png](https://mrkr.io/s/6066232646a0ab2067a85ee5/2)](https://mrkr.io/s/6066232646a0ab2067a85ee5/0)

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced](https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced)

<table><tr><td><strong>Browser</strong></td><td>Chrome 89.0.4389.90</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 669</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by ChristianAF** [comment]
Also if payment is accepted:
![image](https://user-images.githubusercontent.com/43881685/114231358-b9e29600-9950-11eb-886b-9c65055e888f.png)

this is V2

**Comment by msaggiorato** [comment]
After the fixes i did for WPML I'm not able to reproduce either of these issues.
