### ISSUE TITLE
V2 - Multicurrency - Price based on country - Amazon pay button is not refreshing on Cart page

### ISSUE THREAD

**Issue by ChristianAF** [saucal/woocommerce-gateway-amazon-pay#95]
**Describe the bug**
In cases that Amazon pay is not accepting a currency the button should not be present on the cart page or Checkout page.
In this test Amazon pay only accepts EUR. And Price based on country is setted to accept USD for United States, and EUR for the rest.

**To Reproduce**
1. Add a product to Cart and go to 'Cart  page'
2. Click on 'Change address' and fill with an US address if currency is EUR, or with another country if currency is USD.
3. Click on Update address
4. Error: if on Cart After updating cart the button should be hide or unhide, dependes on the currency that was switched

**Screen video**

https://user-images.githubusercontent.com/43881685/114233676-172c1680-9954-11eb-93a5-93ea4475dcf3.mp4

**Expected behavior**
button should be refreshed when address is changed on Cart

**Comment by ChristianAF** [comment]
Also on checkout, the login button is not hiding when it should

**Comment by ChristianAF** [comment]
@msaggiorato on checkout when changing address is not refreshing, the notice with the Amazon login is not showing

**Comment by msaggiorato** [comment]
This is strange... Here's a demo of how things look in my local.

https://www.dropbox.com/s/xzxzwrqtni4p8h3/zoom_1.mp4?dl=0
